### PR TITLE
Add RTSP server for v4l2src and appsrc

### PR DESCRIPTION
**Pull request by lbegani**
Earlier the implementation for RTSP was only for specific set of cameras. Have now changed it to support any camera device added as a plugin.

- [x] Test with v4l2src pipeline
- [x] Test with appsrc pipeline
- [x] Test with multiple streams at a time
- [x] Make the pipeline configurable - enc, format, parser etc
- [x] Add plugins for camera devices - realsense, aero bottom
- [x] Test with Avahi publisher

### CODE REVIEW

**Comment by hamishwillee** [comment]
Looks good. Have you got a reviewer you can rely on?

**Comment by lbegani** [comment]
> Looks good. Have you got a reviewer you can rely on?

@hamishwillee No one yet, I usually wait for a while and then merge.  Feel free to add reviewers. Going forward, I plan to add gtest unit test cases that can be run for basic testing .

**Comment by hamishwillee** [comment]
That sounds sensible!

@mrpollo It would be great if we could get some additional help for Lalit in code review. Is there anyone you could suggest we ask?

**Comment by hamishwillee** [comment]
@paytufo Docs are here: https://camera-manager.dronecode.org/en/

Essentially you plug your camera into a linux companion computer and the camera manager provides a MAVLink and RTSP API. If the camera supports Video4Linux (V4L2) API then everything should just work. If not, you will need to write a plugin that maps to whatever linux API your camera supports.

@lbegani Do you happen to know whether this camera support Video4Linux?

**Comment by lbegani** [comment]
@paytufo  Can the camera Xiaomi Yi be connected with the drone's companion board(over USB interface etc) and can it be detected/accessed from a program running in drone. With little understanding of Yi, I think it is not possible. Xiaomi Yi can be controlled by mechanical buttons or by proprietary phone app over wifi. Correct me if my understanding is wrong.

**Comment by paytufo** [comment]
It’s actually possible to control the Yi Camera with bluetoothand wifi, even exist a phyton program who can control everything and share video via RTSP, but I can only use it with Windows. I’ve tried to make it work with MacOs via Terminal and must be work but I can’t get image. Tried to execute the phyton and execute with qgroundcontrol and get no image. I think the app/project names “master-yi” or something like that, I can browse later. Is on github. Will be amazing to load this when the raspi or other linux based computer boot up and the get the video signal in the app.

**Comment by paytufo** [comment]
Here is the URL 
https://github.com/deltaflyer4747/Xiaomi_Yi
This actioncam is really cheap and very “hackeable” you can put it in client mode wifi for example. I inow I can connect via HDMI to the computer and then share it. But will be better without cables, you don’t?

**Comment by lbegani** [comment]
@paytufo If you can write/run a simple c/c++ program to open/read Yi camera device, then I can help you with how you can write plugin for this camera device and integrate it with camera-manager. Let me know once it works.

**Comment by paytufo** [comment]
I’m architect and I haven’t knowledges enough about programing, maybe I can talk with some friends who could does it. What I’m sure is that the windows CC.exe is running and working with VLC. And I thought that this method open the RSTL transmission to other devices connected to the same network, I can even open in my Iphone in a special camera app but not in qgroundcontrol or in VLC in mu MacOs. Maybe like I said, I haven’t knowledges enough. In other way, I’ll try to make this C/C++ with any friend. Thank you very much!!

**Pull request merged**
