### PR TITLE
PR Specify Gstreamer RTSP pipeline from config file

### PR DESCRIPTION
**Pull request by MatejFranceskin**
Add support for Raspberry PI camera by moving RTSP server gstreamer pipeline definition from code to configuration file. This allows to construct pipeline for PI cam, correctly run webcam on Ubuntu and allows to use zero latency setttings for x264 compression.

This change fixes also the following issues:
https://github.com/Dronecode/camera-manager/issues/185
https://github.com/Dronecode/camera-manager/issues/182
https://github.com/Dronecode/camera-manager/issues/178

### CODE REVIEW

**Comment by hamishwillee** [comment]
@lbegani When might you be able to look at this? I appreciate you are busy so this just a request for an ETA.

**Comment by lbegani** [comment]
Earlier there used to be a section in conf file called `gstreamer` - https://github.com/Dronecode/camera-manager/commit/b1d47585f1d9a44621ee7b14ccb1a7dfdd877e02#diff-433b9344bf93705314b7557877731480. Do you think having this will solve your issue? What I am saying is to have both options - specifying gst pipeline or stream formats, available to the users. One of the reason for having stream format option is to export it as one of the camera parameter and enable the user select the format required from QGC. Currently, not all formats [listed  ](https://github.com/Dronecode/camera-manager/blob/master/samples/config/config.sample#L125)  are added in the switch cases , need to do that.

**Comment by MatejFranceskin** [comment]
I agree - I will try to make both ways possible, with idea to allow user to choose for example h264 or h265 stream.
GStreamer section is used for recording pipeline - I think - I will take a look at it again.

**Comment by MatejFranceskin** [comment]
Actually I really don't know how this was intended to be used. For example with my change you can specify "x264enc speed-preset=ultrafast tune=zerolatency" as encoder format. How would you cover all possible options that are there - by creating an "enum" encoding format for each possibility? What about using hardware accelerated vaapi h264 encoding. It would need again a special format? We could have dozens of hardcoded formats only for h264.

**Comment by lbegani** [comment]
I think there are multiple ways of building the pipeline  - 
1. Hardcode the pipeline in conf file
2. Specify the stream format in conf file (gst elements corresponding to that format is fixed)
3. Specify the stream format conf + specify gst elements to be used for that stream format in conf
Option (2) is supported now, ideally all of the options can be supported. As you are working on option (1), I expect not to break the option (2). In all of these,  some of the parameters like width/height/rate etc can come from the URI as well that must be parsed and applied.
Kindly let me know once you are done with the changes, I will review and merge them.

**Comment by MatejFranceskin** [comment]
Sorry for being grumpy - I didn't understand well how it was meant to be used.
I changed it now so that both ways of constructing RTSP pipelines are possible. If the whole pipeline is not specified in the conf file then it works as it was before.

**Comment by lbegani** [comment]
@MatejFranceskin Merged. Thanks.

**Pull request merged**
